
from flask import Blueprint, render_template, request, redirect, url_for
import re
import difflib
glossary_bp = Blueprint("glossary", __name__)

# --- Concept Keywords Dictionary ---
concept_keywords = {
    "additive manufacturing": "#Additive-Manufacturing",
    "ac circuits containing resistance only": "#AC-Circuits-Containing-Resistance-Only",
    "ac cycles": "#AC-Cycles",
    "ackerman steering mechanism": "#Ackerman-Steering-Mechanism",
    "addressing and tag-based programming": "#Addressing-and-tag-based-Programming",
    "alu": "#ALU-Arithmetic-Logic-Unit",
    "analog signal scaling": "#Analog-Signal-Scaling",
    "analog-to-digital conversion": "#Analog-to-Digital-Conversion-ADC",
    "and gate": "#AND-GATE",
    "automatic retraction sequence": "#Automatic-Retraction-Sequence",
    "automatic valve control": "#Automatic-Valve-Control",
    "batch production": "#Batch-Production",
    "block diagrams": "#Block-diagrams",
    "buses": "#BUSES",
    "cad/cam integration": "#CAD-CAM-Integration",
    "canopen node communication": "#CANopen-Node-Communication",
    "capacitance": "#Capacitance",
    "circuit": "#Circuit",
    "closed loop control": "#Closed-loop-control",
    "communication protocols": "#Communication-Protocols",
    "control logic sequences": "#Control-logic-sequences",
    "cpu": "#CPU-Central-Processing-Unit",
    "cu": "#CU-Control-Unit",
    "current": "#Current",
    "current and voltage in resistive circuits": "#Current-and-Voltage-in-Resistive-Circuits",
    "dc and ac current flows": "#DC-and-AC-Current-Flows",
    "digital and analog i/o interfacing": "#Digital-and-Analog-IO-Interfacing",
    "digital signal interpretation": "#Digital-Signal-Interpretation",
    "digital vs. analog input/output": "#Digital-vs-analog-input-output",
    "driving digital outputs": "#Driving-Digital-Outputs",
    "electrodynamometer movements": "#Electrodynamometer-Movements",
    "embedded programming": "#Embedded-Programming-C-Arduino",
    "emf of self-induction": "#EMF-of-Self-Induction",
    "ethercat data exchange": "#EtherCAT-Data-Exchange",
    "feedback and feedforward control": "#Feedback-and-feedforward-Control",
    "feedback-based actuation": "#Feedback-Based-Actuation",
    "fixed resistors": "#Fixed-Resistors",
    "friction": "#Friction",
    "full step mode": "#Full-step-mode",
    "full-wave rectification": "#Full-Wave-Rectification",
    "half step mode": "#Half-step-mode",
    "half-wave rectification": "#Half-Wave-Rectification",
    "heat action": "#Heat-Action",
    "hot-wire and thermocouple meters": "#Hot-Wire-and-Thermocouple-Meters",
    "inductance in dc circuits": "#Inductance-in-DC-Circuits",
    "inductive sensor triggering": "#Inductive-Sensor-Triggering",
    "interlocking for safety": "#Interlocking-for-Safety",
    "jit production": "#Just-In-Time-JIT-Production",
    "kinematics": "#Kinematics",
    "kinematics diagram": "#Kinematics-Diagram",
    "ladder logic and boolean operations": "#Ladder-Logic-and-Boolean-Operations",
    "lean manufacturing": "#Lean-Manufacturing",
    "led colors and wavelengths": "#LED-Colors-and-Wavelengths",
    "led polarity": "#LED-polarity",
    "load tracking capability": "#Load-tracking-capability",
    "manual": "#Manual",
    "mechanical action": "#Mechanical-Action",
    "mechanical drive": "#Mechanical-Drive",
    "mechanisms": "#Mechanisms",
    "memory function in double solenoid valves": "#Memory-Function-in-Double-Solenoid-Valves",
    "microcontroller architecture": "#Microcontroller-Architecture",
    "microcontroller-based system design": "#Microcontroller-Based-System-Design",
    "microstepping control": "#Microstepping-control",
    "modbus rtu": "#Modbus-RTU",
    "modbus tcp": "#Modbus-TCP",
    "motion": "#Motion",
    "moving-vane meter movements": "#Moving-Vane-Meter-Movements",
    "nand gate": "#NAND-GATE",
    "noise elimination": "#Noise-Elimination",
    "nor gate": "#NOR-GATE",
    "not gate": "#NOT-GATE",
    "ohm’s law": "#Ohms-Law",
    "ohms law":"#Ohms-Law",
    "off-delay timer function": "#Off-Delay-Timer-Function",
    "on-delay timer function": "#On-Delay-Timer-Function",
    "open-loop vs. closed-loop control": "#Open-loop-vs-closed-loop-Control",
    "or gate": "#OR-GATE",
    "parallel led circuits": "#Parallel-LED-Circuits",
    "parallel resistors": "#Parallel-Resistors",
    "pn junction diode theory": "#PN-Junction-Diode-Theory",
    "position feedback mechanism": "#Position-feedback-mechanism",
    "power factor": "#Power-Factor",
    "power in resistive circuits": "#Power-in-Resistive-Circuits",
    "power transmission": "#Power-Transmission",
    "pressure": "#Pressure",
    "pressure compensation": "#Pressure-compensation",
    "pressure regulation": "#Pressure-regulation",
    "pressure sequence control": "#Pressure-sequence-control",
    "proximity sensor detection": "#Proximity-Sensor-Detection",
    "profinet cyclic data": "#Profinet-Cyclic-Data",
    "process flow analysis": "#Process-Flow-Analysis",
    "process variables": "#Process-variables-PV",
    "pulse driven rotation": "#Pulse-driven-rotation",
    "pulse width modulation": "#Pulse-Width-Modulation-PWM",
    "quality assurance": "#Quality-Assurance",
    "quality control": "#Quality-Control",
    "rack/chassis-based vs. compact plcs": "#Rack-Chassis-based-vs-Compact-PLCs",
    "reading digital inputs": "#Reading-Digital-Inputs",
    "rectifier type ac voltmeter": "#Rectifier-Type-AC-Voltmeter",
    "reed switch cylinder positioning": "#Reed-Switch-Cylinder-Positioning",
    "registers": "#REGISTERS",
    "relief valve operation": "#Relief-valve-operation",
    "resistance": "#Resistance",
    "resistor tolerance": "#Resistor-Tolerance",
    "review of resistance in ac circuits": "#Review-of-Resistance-in-AC-Circuits",
    "rotary power": "#Rotary-Power",
    "rotational speed": "#Rotational-Speed",    "5/2 directional control valve operation": "#5-2-Directional-Control-Valve-Operation",
    "electrical latching circuit": "#Electrical-latching-circuit",
    "forward bias": "#Forward-bias",
    "function in control system": "#Function-in-Control-System",
    "pid controller": "#Proportional-Integral-Derivative-Controller",
    "reverse bias operation": "#Reverse-Bias-Operation",
    "signal conditioning & electrical isolation": "#Signal-Conditioning-Electrical-Isolation",
    "single-loop vs multi-loop control": "#Single-loop-vs-Multi-loop-Control"
}

# --- Materials Keywords Dictionary ---
material_keywords = {
    "1n4007 rectifier diode": "#1N4007-Rectifier-Diode",
    "24v dc power supply": "#24V-DC-Power-Supply",
    "3/2 directional control valve": "#3-2-Directional-Control-Valve",
    "3d printers": "#3D-Printers",
    "4/2 directional control valve": "#4-2-Directional-Control-Valve",
    "4/3 directional control valve": "#4-3-Directional-Control-Valve",
    "5/2 directional control valve": "#5-2-Directional-Control-Valve",
    "7400 ic nand": "#7400-IC-NAND",
    "7402 ic nor": "#7402-IC-NOR",
    "7408 ic quad 2-input and gate": "#7408-IC-Quad-2-Input-AND-Gate",
    "7404 ic not": "#7404-IC-NOT",
    "7432 ic or": "#7432-IC-OR",
    "actuators": "#Actuators",
    "analog input/output modules": "#Analog-Input-Output-Modules",
    "Arduino": "#Arduino",
    "automatic valve control": "#Automatic-Valve-Control",
    "belt drive": "#Belt-Drive",
    "blue led": "#Blue-LED",
    "breadboard": "#Breadboard",
    "bridge rectifier module": "#Bridge-Rectifier-Module",
    "can interface module": "#CAN-Interface-Module",
    "capacitor": "#Capacitor",
    "carbon film resistor": "#Carbon-Film-Resistor",
    "carbon zinc dry cell batteries": "#Carbon-Zinc-Dry-Cell-Batteries",
    "chain": "#Chain",
    "cnc machines": "#CNC-Machines",
    "coil": "#Coil",
    "computer laptop": "#Computer-Laptop",
    "control pins": "#Control-Pins",
    "control relay": "#Control-Relay",
    "control valves": "#Control-Valves",
    "controllers": "#Controllers",
    "conveyor systems": "#Conveyor-Systems",
    "copper bars": "#Copper-Bars",
    "copper wire": "#Copper-Wire",
    "coupling shaft": "#Coupling-Shaft",
    "cpu module processor": "#CPU-Module-Processor",
    "dht11 sensor": "#DHT11-Sensor",
    "digital input module": "#Digital-Input-Module",
    "digital ohmmeter": "#Digital-Ohmmeter",
    "digital output module": "#Digital-Output-Module",
    "double solenoid 5/2 valve": "#Double-Solenoid-5-2-Valve",
    "driven gear": "#Driven-Gear",
    "driving gear": "#Driving-Gear",
    "electro pneumatic converters": "#Electro-Pneumatic-Converters",
    "electrolytes": "#Electrolytes",
    "electrical terminal block": "#Electrical-Terminal-Block",
    "electrical timer base socket": "#Electrical-Timer-Base-Socket",
    "electronic timer": "#Electronic-Timer",
    "emergency stop switches": "#Emergency-Stop-Switches",
    "ethernet switch": "#Ethernet-Switch",
    "feedback encoder": "#Feedback-Encoder",
    "fieldbus cable": "#Fieldbus-Cable",
    "flow control pumps": "#Flow-Control-Pumps",
    "flowchart diagramming tool": "#Flowchart-Diagramming-Tool",
    "forklifts": "#Forklifts",
    "fossil fuels": "#Fossil-Fuels",
    "full joint": "#Full-Joint",
    "generator": "#Generator",
    "grinder": "#Grinder",
    "green led": "#Green-LED",
    "hot-wire ammeter": "#Hot-Wire-Ammeter",
    "hydraulic turbines": "#Hydraulic-Turbines",
    "inductive proximity sensor": "#Inductive-Proximity-Sensor",
    "indicators gauges": "#Indicators-Gauges",
    "industrial router": "#Industrial-Router",
    "jumper wire": "#Jumper-Wire",
    "lead-acid batteries": "#Lead-Acid-Batteries",
    "led holder": "#LED-Holder",
    "leds": "#LEDs",
    "light emitting diode": "#Light-Emitting-Diode-LED",
    "limit switch sensor": "#Limit-Switch-Sensor",
    "limit switches": "#Limit-Switches",
    "lithium batteries": "#Lithium-Batteries",
    "machine": "#Machine",
    "magnets": "#Magnets",
    "manual": "#Manual",
    "mercury oxide batteries": "#Mercury-Oxide-Batteries",
    "microcontroller demo board": "#Microcontroller-Demo-Board",
    "motor driver module": "#Motor-Driver-Module-L298N",
    "multimeter": "#Multimeter",
    "oscilloscope": "#Oscilloscope",
    "pneumatic cylinder": "#Pneumatic-Cylinder",
    "positioners for valves and dampers": "#Positioners-for-Valves-and-Dampers",
    "potentiometer": "#Potentiometer",
    "potentiometers": "#Potentiometers",
    "power adapter": "#Power-Adapter",
    "power supply module": "#Power-Supply-Module",
    "power supply unit": "#Power-Supply-Unit",
    "pressure compensation": "#Pressure-compensation",
    "pressure gauge": "#Pressure-Gauge",
    "pressure regulator": "#Pressure-Regulator",
    "pressure transducer": "#Pressure-Transducer",
    "pressure relief valve": "#Pressure-relief-valve",
    "projector computer": "#Projector-Computer",
    "proximity sensor": "#Proximity-Sensor",
    "proximity sensors": "#Proximity-Sensors",
    "pulse generator": "#Pulse-Generator",
    "push buttons": "#Push-Buttons-NO-NC",
    "ram": "#RAM",
    "raw materials": "#Raw-Materials",
    "red led": "#Red-LED",
    "reed switch": "#Reed-Switch",
    "relay module": "#Relay-Module",
    "relay modules": "#Relay-Modules",
    "resistor": "#Resistor",
    "resistor kit": "#Resistor-Kit",
    "robotic arms": "#Robotic-Arms",
    "rs485 converter": "#RS485-Converter",
    "sample embedded devices": "#Sample-Embedded-Devices",
    "safety pressure limits": "#Safety-pressure-limits",
    "screw pair": "#Screw-Pair",
    "selector switches": "#Selector-Switches",
    "sensor indicator module": "#Sensor-Indicator-Module",
    "sensor mounting bracket": "#Sensor-Mounting-Bracket",
    "sensors": "#Sensors",
    "sequence valve": "#Sequence-Valve",
    "servo controller": "#Servo-Controller",
    "servo motor": "#Servo-Motor",
    "sheave": "#Sheave",
    "shielded cable": "#Shielded-Cable",
    "signal cable set": "#Signal-Cable-Set",
    "signal conditioner": "#Signal-Conditioner",
    "signal conditioners": "#Signal-Conditioners",
    "silicon": "#Silicon",
    "slides handouts": "#Slides-Handouts",
    "solar panel": "#Solar-Panel",
    "solenoid valve": "#Solenoid-Valve",
    "spherical pair": "#Spherical-Pair",
    "start push button": "#Start-Push-Button",
    "stepper driver module": "#Stepper-Driver-Module",
    "stepper motor": "#Stepper-Motor",
    "stop push button": "#Stop-Push-Button",
    "switch": "#Switch",
    "temperature sensor": "#Temperature-Sensor",
    "terminal": "#Terminal",
    "timer and clock demo circuits": "#Timer-and-Clock-Demo-Circuits",
    "transistors": "#Transistors",
    "voltmeter": "#Voltmeter",
    "wattmeter": "#Wattmeter",
    "welding equipment": "#Welding-Equipment",
    "whiteboard illustrations": "#Whiteboard-Illustrations",
    "wire leads": "#Wire-Leads",
    "wiring tools": "#Wiring-Tools",
    "zener diode": "#Zener-Diode"
}
@glossary_bp.route("/search")
def search():
    query = request.args.get("q", "").strip().lower()
    query = re.sub(r"[^\w\s]", "", query)

    # --- Concepts keywords ---
    closest = difflib.get_close_matches(query, concept_keywords.keys(), n=1, cutoff=0.5)
    if closest:
        return redirect(url_for("glossary.concept_topic") + concept_keywords[closest[0]])

    # --- Materials keywords ---
    closest = difflib.get_close_matches(query, material_keywords.keys(), n=1, cutoff=0.5)
    if closest:
        return redirect(url_for("glossary.material_topic") + material_keywords[closest[0]])

    # --- Default fallback: show result.html ---
    return render_template("glossary/result.html", query=query)


# --- Basic Mode ---
@glossary_bp.route("/concepts")
def concepts():
    return render_template("glossary/concepts.html")

@glossary_bp.route("/materials")
def materials():
    return render_template("glossary/materials.html")

# --- Advance Mode ---
@glossary_bp.route("/concept_topic")
def concept_topic():
    return render_template("glossary/concept_topic.html")

@glossary_bp.route("/material_topic")
def material_topic():
    return render_template("glossary/material_topic.html")
